In [1]:
from glob import glob
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
import polars as pl

In [2]:
pop_xls_file = pd.ExcelFile('data/lsoa_population_data.xlsx')

In [3]:
pop_xls_file.sheet_names

['Contents',
 'Terms and conditions',
 'Notes and definitions',
 'Mid-2020 Persons',
 'Mid-2020 Males',
 'Mid-2020 Females',
 'Median Age',
 'Related publications']

In [4]:
pop_df = pd.read_excel('data\lsoa_population_data.xlsx', sheet_name='Mid-2020 Persons', header=4)
pop_df

c:\Users\saqui\.conda\envs\lab\Lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

,LSOA Code,LSOA Name,LA Code (2018 boundaries),LA name (2018 boundaries),LA Code (2021 boundaries),LA name (2021 boundaries),All Ages,0,1,2,...,81,82,83,84,85,86,87,88,89,90+
0,E01011949,Hartlepool 009A,E06000001,Hartlepool,E06000001,Hartlepool,1944,20,32,22,...,2,9,14,9,8,7,9,2,2,7
1,E01011950,Hartlepool 008A,E06000001,Hartlepool,E06000001,Hartlepool,1298,14,18,15,...,5,3,1,2,2,2,3,2,1,4
2,E01011951,Hartlepool 007A,E06000001,Hartlepool,E06000001,Hartlepool,1208,18,13,12,...,10,7,2,4,4,5,1,1,4,2
3,E01011952,Hartlepool 002A,E06000001,Hartlepool,E06000001,Hartlepool,1724,23,20,32,...,10,13,14,7,17,18,12,10,8,67
4,E01011953,Hartlepool 002B,E06000001,Hartlepool,E06000001,Hartlepool,2026,27,20,32,...,4,6,6,10,1,2,4,1,4,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34748,W01001320,Merthyr Tydfil 007C,W06000024,Merthyr Tydfil,W06000024,Merthyr Tydfil,1430,17,15,11,...,3,3,3,8,11,9,2,6,9,10
34749,W01001321,Merthyr Tydfil 007D,W06000024,Merthyr Tydfil,W06000024,Merthyr Tydfil,1576,21,19,16,...,2,9,3,7,7,3,10,2,3,12
34750,W01001322,Merthyr Tydfil 007E,W06000024,Merthyr Tydfil,W06000024,Merthyr Tydfil,1626,24,23,22,...,10,9,8,4,8,2,6,1,3,15
34751,W01001324,Merthyr Tydfil 003E,W06000024,Merthyr Tydfil,W06000024,Merthyr Tydfil,2106,19,20,32,...,20,16,16,15,15,12,7,6,8,34
34752,W01001898,Merthyr Tydfil 008F,W06000024,Merthyr Tydfil,W06000024,Merthyr Tydfil,1485,13,15,11,...,10,3,5,9,8,4,4,6,3,6

In [5]:
pop_df.shape

(34753, 98)

In [6]:
pop_df.drop(['LA Code (2018 boundaries)', 'LA name (2018 boundaries)', 
             'LA Code (2021 boundaries)', 'LA name (2021 boundaries)'], 
            axis=1, inplace=True, errors='ignore')

In [7]:
crime_df = pd.read_csv('clean_data\clean_data_v2.csv')
crime_df

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Outcome type
0,c9e13644419c09d866b0677c611c270a7ec07469b07b22...,2020-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.350371,51.391561,On or near Supermarket,E01014468,Bath and North East Somerset 006D,Robbery,Investigation complete; no suspect identified
1,b56fb9a76ae74d64bcf2a977260f288ecc0368c287c003...,2020-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.360522,51.381127,On or near Shopping Area,E01014370,Bath and North East Somerset 007A,Public order,Further investigation is not in the public int...
2,a645e84c245557bc94c24543bc3fbb001da8bf58c0aa8a...,2020-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.359175,51.383451,On or near Parking Area,E01014370,Bath and North East Somerset 007A,Robbery,Suspect charged
3,adb977ce325d741b951aee2b769015322b74f857ce81b7...,2020-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.359175,51.383451,On or near Parking Area,E01014370,Bath and North East Somerset 007A,Shoplifting,Suspect charged
4,b213f886ce58f48c9ca2c39745ab1b8a1825e3239a6ae6...,2020-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.359175,51.383451,On or near Parking Area,E01014370,Bath and North East Somerset 007A,Shoplifting,Suspect charged
...,...,...,...,...,...,...,...,...,...,...,...
2130544,e5ad1fe3d37c380049cd9b41335af39a3b90efa87cca84...,2023-01,Wiltshire Police,Wiltshire Police,-1.759022,50.994660,On or near,E01031995,Wiltshire 062E,Other theft,Investigation complete; no suspect identified
2130545,474af4ae9e4f8813c2e5d983d663bb4e1347d1df474a7d...,2023-01,Wiltshire Police,Wiltshire Police,-1.759022,50.994660,On or near,E01031995,Wiltshire 062E,Other theft,Investigation complete; no suspect identified
2130546,7b01c0f45837c1cb1c75d03f422bc6e34e05148cf6d973...,2023-01,Wiltshire Police,Wiltshire Police,-1.759022,50.994660,On or near,E01031995,Wiltshire 062E,Other theft,Investigation complete; no suspect identified
2130547,2aa6988775439e9c1b52f17d13d6e434e0f3c91b70fed0...,2023-01,Wiltshire Police,Wiltshire Police,-1.750954,50.992992,On or near The Borough,E01031995,Wiltshire 062E,Shoplifting,Investigation complete; no suspect identified
2130548,15fab599887a2d8b9312d595c60dc1f74fea52277f99e9...,2023-01,Wiltshire Police,Wiltshire Police,-1.748516,50.993355,On or near Green Lane,E01031995,Wiltshire 062E,Vehicle crime,Investigation complete; no suspect identified

In [8]:
crime_df.drop(['Crime ID', 'Reported by'], axis=1, inplace=True, errors='ignore')

In [9]:
crime_df

,Month,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Outcome type
0,2020-02,Avon and Somerset Constabulary,-2.350371,51.391561,On or near Supermarket,E01014468,Bath and North East Somerset 006D,Robbery,Investigation complete; no suspect identified
1,2020-02,Avon and Somerset Constabulary,-2.360522,51.381127,On or near Shopping Area,E01014370,Bath and North East Somerset 007A,Public order,Further investigation is not in the public int...
2,2020-02,Avon and Somerset Constabulary,-2.359175,51.383451,On or near Parking Area,E01014370,Bath and North East Somerset 007A,Robbery,Suspect charged
3,2020-02,Avon and Somerset Constabulary,-2.359175,51.383451,On or near Parking Area,E01014370,Bath and North East Somerset 007A,Shoplifting,Suspect charged
4,2020-02,Avon and Somerset Constabulary,-2.359175,51.383451,On or near Parking Area,E01014370,Bath and North East Somerset 007A,Shoplifting,Suspect charged
...,...,...,...,...,...,...,...,...,...
2130544,2023-01,Wiltshire Police,-1.759022,50.994660,On or near,E01031995,Wiltshire 062E,Other theft,Investigation complete; no suspect identified
2130545,2023-01,Wiltshire Police,-1.759022,50.994660,On or near,E01031995,Wiltshire 062E,Other theft,Investigation complete; no suspect identified
2130546,2023-01,Wiltshire Police,-1.759022,50.994660,On or near,E01031995,Wiltshire 062E,Other theft,Investigation complete; no suspect identified
2130547,2023-01,Wiltshire Police,-1.750954,50.992992,On or near The Borough,E01031995,Wiltshire 062E,Shoplifting,Investigation complete; no suspect identified
2130548,2023-01,Wiltshire Police,-1.748516,50.993355,On or near Green Lane,E01031995,Wiltshire 062E,Vehicle crime,Investigation complete; no suspect identified

In [10]:
crime_df['Outcome type'].unique()

array(['Investigation complete; no suspect identified',
       'Further investigation is not in the public interest',
       'Suspect charged', 'Unable to prosecute suspect',
       'Local resolution', 'Action to be taken by another organisation',
       'Further action is not in the public interest',
       'Offender given a caution',
       'Formal action is not in the public interest',
       'Suspect charged as part of another case',
       'Offender given a drugs possession warning',
       'Offender given penalty notice'], dtype=object)

In [11]:
crime_df['Conviction'] = crime_df['Outcome type'].apply(lambda x: 'prosecuted' if 'charged' in x else 'not-prosecuted')

In [12]:
crime_df

,Month,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Outcome type,Conviction
0,2020-02,Avon and Somerset Constabulary,-2.350371,51.391561,On or near Supermarket,E01014468,Bath and North East Somerset 006D,Robbery,Investigation complete; no suspect identified,not-prosecuted
1,2020-02,Avon and Somerset Constabulary,-2.360522,51.381127,On or near Shopping Area,E01014370,Bath and North East Somerset 007A,Public order,Further investigation is not in the public int...,not-prosecuted
2,2020-02,Avon and Somerset Constabulary,-2.359175,51.383451,On or near Parking Area,E01014370,Bath and North East Somerset 007A,Robbery,Suspect charged,prosecuted
3,2020-02,Avon and Somerset Constabulary,-2.359175,51.383451,On or near Parking Area,E01014370,Bath and North East Somerset 007A,Shoplifting,Suspect charged,prosecuted
4,2020-02,Avon and Somerset Constabulary,-2.359175,51.383451,On or near Parking Area,E01014370,Bath and North East Somerset 007A,Shoplifting,Suspect charged,prosecuted
...,...,...,...,...,...,...,...,...,...,...
2130544,2023-01,Wiltshire Police,-1.759022,50.994660,On or near,E01031995,Wiltshire 062E,Other theft,Investigation complete; no suspect identified,not-prosecuted
2130545,2023-01,Wiltshire Police,-1.759022,50.994660,On or near,E01031995,Wiltshire 062E,Other theft,Investigation complete; no suspect identified,not-prosecuted
2130546,2023-01,Wiltshire Police,-1.759022,50.994660,On or near,E01031995,Wiltshire 062E,Other theft,Investigation complete; no suspect identified,not-prosecuted
2130547,2023-01,Wiltshire Police,-1.750954,50.992992,On or near The Borough,E01031995,Wiltshire 062E,Shoplifting,Investigation complete; no suspect identified,not-prosecuted
2130548,2023-01,Wiltshire Police,-1.748516,50.993355,On or near Green Lane,E01031995,Wiltshire 062E,Vehicle crime,Investigation complete; no suspect identified,not-prosecuted

In [14]:
pop_df

,LSOA Code,LSOA Name,All Ages,0,1,2,3,4,5,6,...,81,82,83,84,85,86,87,88,89,90+
0,E01011949,Hartlepool 009A,1944,20,32,22,17,27,31,23,...,2,9,14,9,8,7,9,2,2,7
1,E01011950,Hartlepool 008A,1298,14,18,15,13,11,10,17,...,5,3,1,2,2,2,3,2,1,4
2,E01011951,Hartlepool 007A,1208,18,13,12,9,16,10,11,...,10,7,2,4,4,5,1,1,4,2
3,E01011952,Hartlepool 002A,1724,23,20,32,19,28,19,29,...,10,13,14,7,17,18,12,10,8,67
4,E01011953,Hartlepool 002B,2026,27,20,32,39,27,44,34,...,4,6,6,10,1,2,4,1,4,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34748,W01001320,Merthyr Tydfil 007C,1430,17,15,11,9,6,20,18,...,3,3,3,8,11,9,2,6,9,10
34749,W01001321,Merthyr Tydfil 007D,1576,21,19,16,26,21,24,19,...,2,9,3,7,7,3,10,2,3,12
34750,W01001322,Merthyr Tydfil 007E,1626,24,23,22,26,23,24,20,...,10,9,8,4,8,2,6,1,3,15
34751,W01001324,Merthyr Tydfil 003E,2106,19,20,32,18,29,19,11,...,20,16,16,15,15,12,7,6,8,34
34752,W01001898,Merthyr Tydfil 008F,1485,13,15,11,13,12,16,16,...,10,3,5,9,8,4,4,6,3,6

In [51]:
lsoa_crime_df = crime_df.groupby(['LSOA code', 'LSOA name']).agg({'Month':'count',
                                            'Falls within':', '.join,
                                            'Falls within':'unique',
                                            'Location':', '.join,
                                            'Location':'unique',
                                            'Crime type':', '.join,
                                            'Crime type':'unique',
                                            'Conviction':', '.join}).reset_index()

In [52]:
lsoa_crime_df

,LSOA code,LSOA name,Month,Falls within,Location,Crime type,Conviction
0,E01000001,City of London 001A,45,"[City of London Police, Metropolitan Police Se...","[On or near Parking Area, On or near Conferenc...","[Drugs, Other theft, Violence and sexual offen...","not-prosecuted, not-prosecuted, not-prosecuted..."
1,E01000002,City of London 001B,113,"[City of London Police, Metropolitan Police Se...","[On or near Park/Open Space, On or near Parkin...","[Criminal damage and arson, Other theft, Bicyc...","not-prosecuted, not-prosecuted, not-prosecuted..."
2,E01000003,City of London 001C,16,"[City of London Police, Metropolitan Police Se...","[On or near Shopping Area, On or near Park/Ope...","[Theft from the person, Violence and sexual of...","not-prosecuted, not-prosecuted, not-prosecuted..."
3,E01000005,City of London 001E,184,"[City of London Police, Metropolitan Police Se...","[On or near Pedestrian Subway, On or near Furt...","[Criminal damage and arson, Other theft, Theft...","not-prosecuted, not-prosecuted, not-prosecuted..."
4,E01000006,Barking and Dagenham 016A,11,[Metropolitan Police Service],"[On or near Salisbury Avenue, On or near Sherr...","[Other theft, Vehicle crime, Drugs, Theft from...","not-prosecuted, not-prosecuted, not-prosecuted..."
...,...,...,...,...,...,...,...
33061,W01001954,Cardiff 006F,13,[South Wales Police],"[On or near , On or near Taff Terrace, On or n...","[Shoplifting, Vehicle crime, Bicycle theft, Cr...","not-prosecuted, not-prosecuted, not-prosecuted..."
33062,W01001955,Swansea 025F,1255,[South Wales Police],"[On or near Nightclub, On or near Shopping Are...","[Bicycle theft, Criminal damage and arson, Sho...","not-prosecuted, not-prosecuted, not-prosecuted..."
33063,W01001956,Swansea 023E,62,[South Wales Police],"[On or near Supermarket, On or near Parking Ar...","[Shoplifting, Criminal damage and arson, Other...","not-prosecuted, not-prosecuted, not-prosecuted..."
33064,W01001957,Swansea 025G,156,[South Wales Police],"[On or near Supermarket, On or near Prison, On...","[Shoplifting, Violence and sexual offences, Pu...","not-prosecuted, not-prosecuted, prosecuted, pr..."
33065,W01001958,Swansea 025H,142,[South Wales Police],"[On or near Parking Area, On or near Petrol St...","[Vehicle crime, Other theft, Public order, Sho...","not-prosecuted, not-prosecuted, not-prosecuted..."

In [53]:
def word_count(str):
    counts = {}
    words = str.split(', ')
    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1
    return counts

In [54]:
word_count('prosecuted, not-prosecuted, not-prosecuted, not-prosecuted')

{'prosecuted': 1, 'not-prosecuted': 3}

In [55]:
lsoa_crime_df['Conviction'] = lsoa_crime_df['Conviction'].apply(word_count)

In [56]:
lsoa_crime_df

,LSOA code,LSOA name,Month,Falls within,Location,Crime type,Conviction
0,E01000001,City of London 001A,45,"[City of London Police, Metropolitan Police Se...","[On or near Parking Area, On or near Conferenc...","[Drugs, Other theft, Violence and sexual offen...",{'not-prosecuted': 45}
1,E01000002,City of London 001B,113,"[City of London Police, Metropolitan Police Se...","[On or near Park/Open Space, On or near Parkin...","[Criminal damage and arson, Other theft, Bicyc...","{'not-prosecuted': 110, 'prosecuted': 3}"
2,E01000003,City of London 001C,16,"[City of London Police, Metropolitan Police Se...","[On or near Shopping Area, On or near Park/Ope...","[Theft from the person, Violence and sexual of...",{'not-prosecuted': 16}
3,E01000005,City of London 001E,184,"[City of London Police, Metropolitan Police Se...","[On or near Pedestrian Subway, On or near Furt...","[Criminal damage and arson, Other theft, Theft...","{'not-prosecuted': 175, 'prosecuted': 9}"
4,E01000006,Barking and Dagenham 016A,11,[Metropolitan Police Service],"[On or near Salisbury Avenue, On or near Sherr...","[Other theft, Vehicle crime, Drugs, Theft from...",{'not-prosecuted': 11}
...,...,...,...,...,...,...,...
33061,W01001954,Cardiff 006F,13,[South Wales Police],"[On or near , On or near Taff Terrace, On or n...","[Shoplifting, Vehicle crime, Bicycle theft, Cr...",{'not-prosecuted': 13}
33062,W01001955,Swansea 025F,1255,[South Wales Police],"[On or near Nightclub, On or near Shopping Are...","[Bicycle theft, Criminal damage and arson, Sho...","{'not-prosecuted': 1079, 'prosecuted': 176}"
33063,W01001956,Swansea 023E,62,[South Wales Police],"[On or near Supermarket, On or near Parking Ar...","[Shoplifting, Criminal damage and arson, Other...",{'not-prosecuted': 62}
33064,W01001957,Swansea 025G,156,[South Wales Police],"[On or near Supermarket, On or near Prison, On...","[Shoplifting, Violence and sexual offences, Pu...","{'not-prosecuted': 131, 'prosecuted': 25}"
33065,W01001958,Swansea 025H,142,[South Wales Police],"[On or near Parking Area, On or near Petrol St...","[Vehicle crime, Other theft, Public order, Sho...","{'not-prosecuted': 124, 'prosecuted': 18}"

In [57]:
col = lsoa_crime_df['Conviction'].apply(lambda x: pd.Series(x))

In [58]:
col

       not-prosecuted  prosecuted
0                45.0         NaN
1               110.0         3.0
2                16.0         NaN
3               175.0         9.0
4                11.0         NaN
...               ...         ...
33061            13.0         NaN
33062          1079.0       176.0
33063            62.0         NaN
33064           131.0        25.0
33065           124.0        18.0

[33066 rows x 2 columns]

In [59]:
df = pd.concat([lsoa_crime_df, col], axis=1)
df

,LSOA code,LSOA name,Month,Falls within,Location,Crime type,Conviction,not-prosecuted,prosecuted
0,E01000001,City of London 001A,45,"[City of London Police, Metropolitan Police Se...","[On or near Parking Area, On or near Conferenc...","[Drugs, Other theft, Violence and sexual offen...",{'not-prosecuted': 45},45.0,NaN
1,E01000002,City of London 001B,113,"[City of London Police, Metropolitan Police Se...","[On or near Park/Open Space, On or near Parkin...","[Criminal damage and arson, Other theft, Bicyc...","{'not-prosecuted': 110, 'prosecuted': 3}",110.0,3.0
2,E01000003,City of London 001C,16,"[City of London Police, Metropolitan Police Se...","[On or near Shopping Area, On or near Park/Ope...","[Theft from the person, Violence and sexual of...",{'not-prosecuted': 16},16.0,NaN
3,E01000005,City of London 001E,184,"[City of London Police, Metropolitan Police Se...","[On or near Pedestrian Subway, On or near Furt...","[Criminal damage and arson, Other theft, Theft...","{'not-prosecuted': 175, 'prosecuted': 9}",175.0,9.0
4,E01000006,Barking and Dagenham 016A,11,[Metropolitan Police Service],"[On or near Salisbury Avenue, On or near Sherr...","[Other theft, Vehicle crime, Drugs, Theft from...",{'not-prosecuted': 11},11.0,NaN
...,...,...,...,...,...,...,...,...,...
33061,W01001954,Cardiff 006F,13,[South Wales Police],"[On or near , On or near Taff Terrace, On or n...","[Shoplifting, Vehicle crime, Bicycle theft, Cr...",{'not-prosecuted': 13},13.0,NaN
33062,W01001955,Swansea 025F,1255,[South Wales Police],"[On or near Nightclub, On or near Shopping Are...","[Bicycle theft, Criminal damage and arson, Sho...","{'not-prosecuted': 1079, 'prosecuted': 176}",1079.0,176.0
33063,W01001956,Swansea 023E,62,[South Wales Police],"[On or near Supermarket, On or near Parking Ar...","[Shoplifting, Criminal damage and arson, Other...",{'not-prosecuted': 62},62.0,NaN
33064,W01001957,Swansea 025G,156,[South Wales Police],"[On or near Supermarket, On or near Prison, On...","[Shoplifting, Violence and sexual offences, Pu...","{'not-prosecuted': 131, 'prosecuted': 25}",131.0,25.0
33065,W01001958,Swansea 025H,142,[South Wales Police],"[On or near Parking Area, On or near Petrol St...","[Vehicle crime, Other theft, Public order, Sho...","{'not-prosecuted': 124, 'prosecuted': 18}",124.0,18.0

In [60]:
df[['Falls within', 'Location', 'Crime type']] = df[['Falls within', 'Location', 'Crime type']].applymap(lambda x: ', '.join(x))
df

,LSOA code,LSOA name,Month,Falls within,Location,Crime type,Conviction,not-prosecuted,prosecuted
0,E01000001,City of London 001A,45,"City of London Police, Metropolitan Police Ser...","On or near Parking Area, On or near Conference...","Drugs, Other theft, Violence and sexual offenc...",{'not-prosecuted': 45},45.0,NaN
1,E01000002,City of London 001B,113,"City of London Police, Metropolitan Police Ser...","On or near Park/Open Space, On or near Parking...","Criminal damage and arson, Other theft, Bicycl...","{'not-prosecuted': 110, 'prosecuted': 3}",110.0,3.0
2,E01000003,City of London 001C,16,"City of London Police, Metropolitan Police Ser...","On or near Shopping Area, On or near Park/Open...","Theft from the person, Violence and sexual off...",{'not-prosecuted': 16},16.0,NaN
3,E01000005,City of London 001E,184,"City of London Police, Metropolitan Police Ser...","On or near Pedestrian Subway, On or near Furth...","Criminal damage and arson, Other theft, Theft ...","{'not-prosecuted': 175, 'prosecuted': 9}",175.0,9.0
4,E01000006,Barking and Dagenham 016A,11,Metropolitan Police Service,"On or near Salisbury Avenue, On or near Sherry...","Other theft, Vehicle crime, Drugs, Theft from ...",{'not-prosecuted': 11},11.0,NaN
...,...,...,...,...,...,...,...,...,...
33061,W01001954,Cardiff 006F,13,South Wales Police,"On or near , On or near Taff Terrace, On or ne...","Shoplifting, Vehicle crime, Bicycle theft, Cri...",{'not-prosecuted': 13},13.0,NaN
33062,W01001955,Swansea 025F,1255,South Wales Police,"On or near Nightclub, On or near Shopping Area...","Bicycle theft, Criminal damage and arson, Shop...","{'not-prosecuted': 1079, 'prosecuted': 176}",1079.0,176.0
33063,W01001956,Swansea 023E,62,South Wales Police,"On or near Supermarket, On or near Parking Are...","Shoplifting, Criminal damage and arson, Other ...",{'not-prosecuted': 62},62.0,NaN
33064,W01001957,Swansea 025G,156,South Wales Police,"On or near Supermarket, On or near Prison, On ...","Shoplifting, Violence and sexual offences, Pub...","{'not-prosecuted': 131, 'prosecuted': 25}",131.0,25.0
33065,W01001958,Swansea 025H,142,South Wales Police,"On or near Parking Area, On or near Petrol Sta...","Vehicle crime, Other theft, Public order, Shop...","{'not-prosecuted': 124, 'prosecuted': 18}",124.0,18.0

In [85]:
pop_crime_location_df = df.merge(pop_df, left_on=['LSOA code', 'LSOA name'], right_on=['LSOA Code', 'LSOA Name'], how='left')
pop_crime_location_df

,LSOA code,LSOA name,Month,Falls within,Location,Crime type,Conviction,not-prosecuted,prosecuted,LSOA Code,...,81,82,83,84,85,86,87,88,89,90+
0,E01000001,City of London 001A,45,"City of London Police, Metropolitan Police Ser...","On or near Parking Area, On or near Conference...","Drugs, Other theft, Violence and sexual offenc...",{'not-prosecuted': 45},45.0,NaN,E01000001,...,14,11,10,6,8,1,6,2,3,45
1,E01000002,City of London 001B,113,"City of London Police, Metropolitan Police Ser...","On or near Park/Open Space, On or near Parking...","Criminal damage and arson, Other theft, Bicycl...","{'not-prosecuted': 110, 'prosecuted': 3}",110.0,3.0,E01000002,...,17,13,16,3,10,1,5,1,8,29
2,E01000003,City of London 001C,16,"City of London Police, Metropolitan Police Ser...","On or near Shopping Area, On or near Park/Open...","Theft from the person, Violence and sexual off...",{'not-prosecuted': 16},16.0,NaN,E01000003,...,6,17,11,4,12,6,8,5,8,23
3,E01000005,City of London 001E,184,"City of London Police, Metropolitan Police Ser...","On or near Pedestrian Subway, On or near Furth...","Criminal damage and arson, Other theft, Theft ...","{'not-prosecuted': 175, 'prosecuted': 9}",175.0,9.0,E01000005,...,13,3,0,8,8,1,8,1,0,9
4,E01000006,Barking and Dagenham 016A,11,Metropolitan Police Service,"On or near Salisbury Avenue, On or near Sherry...","Other theft, Vehicle crime, Drugs, Theft from ...",{'not-prosecuted': 11},11.0,NaN,E01000006,...,6,12,7,1,3,3,3,3,1,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33061,W01001954,Cardiff 006F,13,South Wales Police,"On or near , On or near Taff Terrace, On or ne...","Shoplifting, Vehicle crime, Bicycle theft, Cri...",{'not-prosecuted': 13},13.0,NaN,W01001954,...,6,16,14,12,13,10,10,13,7,24
33062,W01001955,Swansea 025F,1255,South Wales Police,"On or near Nightclub, On or near Shopping Area...","Bicycle theft, Criminal damage and arson, Shop...","{'not-prosecuted': 1079, 'prosecuted': 176}",1079.0,176.0,W01001955,...,2,4,4,10,4,5,4,3,3,11
33063,W01001956,Swansea 023E,62,South Wales Police,"On or near Supermarket, On or near Parking Are...","Shoplifting, Criminal damage and arson, Other ...",{'not-prosecuted': 62},62.0,NaN,W01001956,...,13,15,12,11,17,10,8,8,2,5
33064,W01001957,Swansea 025G,156,South Wales Police,"On or near Supermarket, On or near Prison, On ...","Shoplifting, Violence and sexual offences, Pub...","{'not-prosecuted': 131, 'prosecuted': 25}",131.0,25.0,W01001957,...,11,4,3,5,7,5,3,7,1,8
33065,W01001958,Swansea 025H,142,South Wales Police,"On or near Parking Area, On or near Petrol Sta...","Vehicle crime, Other theft, Public order, Shop...","{'not-prosecuted': 124, 'prosecuted': 18}",124.0,18.0,W01001958,...,5,9,6,2,6,6,3,2,2,11

In [86]:
pop_crime_location_df.rename({'Month':'Crime Count'}, axis=1, inplace=True, errors='ignore')

In [87]:
pop_crime_location_df = pop_crime_location_df[['LSOA code', 'LSOA name', 'Crime Count', 'Crime type', 'Location', 'Falls within', 'All Ages', 'not-prosecuted', 'prosecuted']]
pop_crime_location_df

,LSOA code,LSOA name,Crime Count,Crime type,Location,Falls within,All Ages,not-prosecuted,prosecuted
0,E01000001,City of London 001A,45,"Drugs, Other theft, Violence and sexual offenc...","On or near Parking Area, On or near Conference...","City of London Police, Metropolitan Police Ser...",1749,45.0,NaN
1,E01000002,City of London 001B,113,"Criminal damage and arson, Other theft, Bicycl...","On or near Park/Open Space, On or near Parking...","City of London Police, Metropolitan Police Ser...",1678,110.0,3.0
2,E01000003,City of London 001C,16,"Theft from the person, Violence and sexual off...","On or near Shopping Area, On or near Park/Open...","City of London Police, Metropolitan Police Ser...",1900,16.0,NaN
3,E01000005,City of London 001E,184,"Criminal damage and arson, Other theft, Theft ...","On or near Pedestrian Subway, On or near Furth...","City of London Police, Metropolitan Police Ser...",2181,175.0,9.0
4,E01000006,Barking and Dagenham 016A,11,"Other theft, Vehicle crime, Drugs, Theft from ...","On or near Salisbury Avenue, On or near Sherry...",Metropolitan Police Service,2117,11.0,NaN
...,...,...,...,...,...,...,...,...,...
33061,W01001954,Cardiff 006F,13,"Shoplifting, Vehicle crime, Bicycle theft, Cri...","On or near , On or near Taff Terrace, On or ne...",South Wales Police,1497,13.0,NaN
33062,W01001955,Swansea 025F,1255,"Bicycle theft, Criminal damage and arson, Shop...","On or near Nightclub, On or near Shopping Area...",South Wales Police,2050,1079.0,176.0
33063,W01001956,Swansea 023E,62,"Shoplifting, Criminal damage and arson, Other ...","On or near Supermarket, On or near Parking Are...",South Wales Police,2185,62.0,NaN
33064,W01001957,Swansea 025G,156,"Shoplifting, Violence and sexual offences, Pub...","On or near Supermarket, On or near Prison, On ...",South Wales Police,1035,131.0,25.0
33065,W01001958,Swansea 025H,142,"Vehicle crime, Other theft, Public order, Shop...","On or near Parking Area, On or near Petrol Sta...",South Wales Police,1661,124.0,18.0

In [88]:
import re
pop_crime_location_df['Location'] = pop_crime_location_df['Location'].apply(lambda x: re.sub("On or near ", "", x))

C:\Users\saqui\AppData\Local\Temp\ipykernel_6228\2782502493.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop_crime_location_df['Location'] = pop_crime_location_df['Location'].apply(lambda x: re.sub("On or near ", "", x))

In [89]:
pop_crime_location_df

,LSOA code,LSOA name,Crime Count,Crime type,Location,Falls within,All Ages,not-prosecuted,prosecuted
0,E01000001,City of London 001A,45,"Drugs, Other theft, Violence and sexual offenc...","Parking Area, Conference/Exhibition Centre, Al...","City of London Police, Metropolitan Police Ser...",1749,45.0,NaN
1,E01000002,City of London 001B,113,"Criminal damage and arson, Other theft, Bicycl...","Park/Open Space, Parking Area, Conference/Exhi...","City of London Police, Metropolitan Police Ser...",1678,110.0,3.0
2,E01000003,City of London 001C,16,"Theft from the person, Violence and sexual off...","Shopping Area, Park/Open Space, Brackley Stree...","City of London Police, Metropolitan Police Ser...",1900,16.0,NaN
3,E01000005,City of London 001E,184,"Criminal damage and arson, Other theft, Theft ...","Pedestrian Subway, Further/Higher Educational ...","City of London Police, Metropolitan Police Ser...",2181,175.0,9.0
4,E01000006,Barking and Dagenham 016A,11,"Other theft, Vehicle crime, Drugs, Theft from ...","Salisbury Avenue, Sherry Mews, Rosslyn Road, G...",Metropolitan Police Service,2117,11.0,NaN
...,...,...,...,...,...,...,...,...,...
33061,W01001954,Cardiff 006F,13,"Shoplifting, Vehicle crime, Bicycle theft, Cri...",", Taff Terrace, Ty Nant Road, Windsor Crescent...",South Wales Police,1497,13.0,NaN
33062,W01001955,Swansea 025F,1255,"Bicycle theft, Criminal damage and arson, Shop...","Nightclub, Shopping Area, Parking Area, Bus/Co...",South Wales Police,2050,1079.0,176.0
33063,W01001956,Swansea 023E,62,"Shoplifting, Criminal damage and arson, Other ...","Supermarket, Parking Area, Clyne View, Stephen...",South Wales Police,2185,62.0,NaN
33064,W01001957,Swansea 025G,156,"Shoplifting, Violence and sexual offences, Pub...","Supermarket, Prison, Parking Area, Pedestrian ...",South Wales Police,1035,131.0,25.0
33065,W01001958,Swansea 025H,142,"Vehicle crime, Other theft, Public order, Shop...","Parking Area, Petrol Station, Supermarket, Con...",South Wales Police,1661,124.0,18.0

In [92]:
pop_crime_location_df

,LSOA code,LSOA name,Crime Count,Crime type,Location,Falls within,All Ages,not-prosecuted,prosecuted
0,E01000001,City of London 001A,45,"Drugs, Other theft, Violence and sexual offenc...","Parking Area, Conference/Exhibition Centre, Al...","City of London Police, Metropolitan Police Ser...",1749,45.0,NaN
1,E01000002,City of London 001B,113,"Criminal damage and arson, Other theft, Bicycl...","Park/Open Space, Parking Area, Conference/Exhi...","City of London Police, Metropolitan Police Ser...",1678,110.0,3.0
2,E01000003,City of London 001C,16,"Theft from the person, Violence and sexual off...","Shopping Area, Park/Open Space, Brackley Stree...","City of London Police, Metropolitan Police Ser...",1900,16.0,NaN
3,E01000005,City of London 001E,184,"Criminal damage and arson, Other theft, Theft ...","Pedestrian Subway, Further/Higher Educational ...","City of London Police, Metropolitan Police Ser...",2181,175.0,9.0
4,E01000006,Barking and Dagenham 016A,11,"Other theft, Vehicle crime, Drugs, Theft from ...","Salisbury Avenue, Sherry Mews, Rosslyn Road, G...",Metropolitan Police Service,2117,11.0,NaN
...,...,...,...,...,...,...,...,...,...
33061,W01001954,Cardiff 006F,13,"Shoplifting, Vehicle crime, Bicycle theft, Cri...",", Taff Terrace, Ty Nant Road, Windsor Crescent...",South Wales Police,1497,13.0,NaN
33062,W01001955,Swansea 025F,1255,"Bicycle theft, Criminal damage and arson, Shop...","Nightclub, Shopping Area, Parking Area, Bus/Co...",South Wales Police,2050,1079.0,176.0
33063,W01001956,Swansea 023E,62,"Shoplifting, Criminal damage and arson, Other ...","Supermarket, Parking Area, Clyne View, Stephen...",South Wales Police,2185,62.0,NaN
33064,W01001957,Swansea 025G,156,"Shoplifting, Violence and sexual offences, Pub...","Supermarket, Prison, Parking Area, Pedestrian ...",South Wales Police,1035,131.0,25.0
33065,W01001958,Swansea 025H,142,"Vehicle crime, Other theft, Public order, Shop...","Parking Area, Petrol Station, Supermarket, Con...",South Wales Police,1661,124.0,18.0

In [114]:
from datetime import datetime


def save_file(dataframe):
    current_datetime = datetime.now().strftime('%Y%m%d_%H%M%S')
    file_name = 'pop_crime'
    output_file = f'clean_data/{file_name}_{current_datetime}.csv'
    dataframe.to_csv(output_file, index=False)
    
    return output_file

In [115]:
save_file(pop_crime_location_df)

'clean_data/pop_crime_20230520_135654.csv'

In [37]:
pop_crime_location_df.to_csv('clean_data/pop_crime_location_df.csv', index=False)